### ISSUE TITLE
Replaces angle brackets with HTML entities

### ISSUE THREAD

**Issue by Blacksilver42** [Benjol/SE-AutoReviewComments#146] opened 2018-01-18 19:29 UTC
e.g.,

    ###[Q]
    Try making this into a [mcve], please! <3

Results in

    Try making this into a [mcve], please! &lt;3

**Comment by makyen** [comment] 2018-01-28 06:57
This is a duplicate of #109.

**Closed** 2018-01-28 21:13 UTC
