### ISSUE TITLE
'auto' link doesn't show anymore

### ISSUE THREAD

**Issue by Glorfindel83** [Benjol/SE-AutoReviewComments#168] opened 2019-02-21 09:10 UTC
As of today, the userscript isn't working for me (macOS 10.14.3, Firefox 65.0.1, Violentmonkey 2.10.1); the 'auto' link doesn't show anymore. I'm sure it worked yesterday and there have been no updates to my system. Maybe the SE pages have had a structural change breaking the script?

<img width="709" alt="screenshot 2019-02-21 at 10 09 17" src="https://user-images.githubusercontent.com/24611142/53156996-df6d8380-35c0-11e9-95ba-292062c63578.png">

I have little experience debugging userscripts, if you can reproduce the problem, would you mind trying to solve it first?

**Comment by oliversalzburg** [comment] 2019-02-21 09:20
Duplicate of #163

**Closed by oliversalzburg** 2019-02-21 09:20 UTC
