### ISSUE TITLE
"Auto" link not apperaing anymore

### ISSUE THREAD

**Issue by a-stone-arachnid** [Benjol/SE-AutoReviewComments#167] opened 2019-02-21 01:47 UTC
Stack Exchange removed the class `.comment-help-link` on the comment help link, so that needs to be updated to `.js-comment-help-link` for it to work.

Using version 1.4.4 on TamperMonkey and Waterfox.

**Comment by dtgriscom** [comment] 2019-02-21 03:12
Confirmed, and I've just discovered how much I use this tool...

(A belated thanks!)

**Comment by Benjol** [comment] 2019-02-21 06:13
Duplicate of #163, fix on the way...

**Closed by Benjol** 2019-02-21 06:13 UTC
