### ISSUE TITLE
Extension has stopped working

### ISSUE THREAD

**Issue by barmar** [Benjol/SE-AutoReviewComments#169] opened 2019-02-21 22:03 UTC
A couple of days ago, this stopped working when commenting on questions or answers. The "auto" link no longer shows up. It still appears below the "Edit Summary" field, though (I've never needed it there -- Chrome's built-in autocomplete is sufficient).

TamperMonkey updated around the same time, so I thought it might be related, but I disabled TamperMonkey and it didn't help. I haven't made any other changes to Chrome recently.

**Comment by Paulster2** [comment] 2019-02-22 02:49
Just to confirm, I've experienced the same issue. I've uninstalled/reinstalled without resolution.

**Comment by dont-panic-42** [comment] 2019-02-22 02:51
Me too, Chrome Version 72.0.3626.109, macOS 10.14.2.  Started today, I was just reconfiguring it yesterday.

**Comment by RoryMcCrossan** [comment] 2019-02-22 09:34
Also having the same issue.

**Comment by Benjol** [comment] 2019-02-22 09:50
Corrected here, but I haven't yet uploaded the new version to the Store. Probably tomorrow.

**Comment by oliversalzburg** [comment] 2019-02-22 13:19
Duplicate of #163

**Closed by oliversalzburg** 2019-02-22 13:19 UTC
