### ISSUE TITLE
Welcome text no longer automatically inserted

### ISSUE THREAD

**Issue by Julian-O** [Benjol/SE-AutoReviewComments#94] opened 2015-03-31 00:29 UTC
I am using 1.4.0 on Chrome on one of the mid-sized Stack Exchange sites.

(Weird: I don't remember updating to 1.4. But everything looks different now, since I returned from holidays. But Chrome Web Store is still at 1.3.3. Huh. Confused.)

The user's details (how long they have been a member) are no longer displayed and the Welcome message is no longer inserted.

**Comment by oliversalzburg** [comment] 2015-03-31 08:01
Duplicate of #87 Is fixed in 1.4.1

**Closed by oliversalzburg** 2015-03-31 08:01 UTC
