### ISSUE TITLE
Add-on is not compatible with Firefox >= 57/Quantum

### ISSUE THREAD

**Issue by krichter722** [Benjol/SE-AutoReviewComments#148] opened 2018-02-15 15:42 UTC
This applies to v1.4.2-18-g20e6aa3 as well.

**Comment by oliversalzburg** [comment] 2018-02-15 16:34
You probably want to use the userscript at this point.

**Comment by makyen** [comment] 2018-02-15 17:18
This is effectively a duplicate of #130.

As the README.md says, the Firefox extension is "is deprecated until further notice".

However, if someone wanted to work on it, it's quite likely that the code which is currently used for the Chrome extension would work in Firefox with no/minimal changes.

**Comment by oliversalzburg** [comment] 2018-03-15 08:46
We should probably remove the old Firefox extension from the build and publications to avoid further confusion. I agree with @makyen that this is a duplicate of #130.

**Closed by oliversalzburg** 2018-03-15 08:46 UTC
Labels: affects:firefox, status:duplicate, type:enhancement
